services:
  sonarqube:
    image: sonarqube:10.7.0-developer
    container_name: sonarqube
    ports:
      - 9000:9000
    options: --health-cmd "grep -Fq \"SonarQube is operational\" /opt/sonarqube/logs/sonar.log" --health-interval 10s --health-timeout 5s --health-retries 10
    #volumes:
    #  - ./sonarqube_data:/opt/sonarqube/data
    #  - ./sonarqube_logs:/opt/sonarqube/logs
    #  - ./sonarqube_extensions:/opt/sonarqube/extensions

  https-proxy:
    image: nginx
    container_name: https-proxy
    ports:
      - 4443:4443
    volumes:
      - $GITHUB_WORKSPACE/nginx.conf:/etc/nginx/nginx.conf:ro
      - $GITHUB_WORKSPACE/client_certs/ca.crt:/etc/nginx/client_certs/ca.crt:ro
      - $GITHUB_WORKSPACE/server_certs/server.crt:/etc/nginx/server.crt:ro
      - $GITHUB_WORKSPACE/server_certs/server.key:/etc/nginx/server.key:ro
    depends_on:
      - sonarqube
#volumes:
#  sonarqube_data:
#  sonarqube_logs:
#  sonarqube_extensions:
  