services:
  sonarqube:
    image: sonarqube:10.7.0-developer
    ports:
      - 9000:9000
    healthcheck:
      test: 'grep -Fq "SonarQube is operational" /opt/sonarqube/logs/sonar.log'
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 2m

  https-proxy:
    image: nginx
    ports:
      - 4443:4443
    volumes:
      - $GITHUB_WORKSPACE/nginx.conf:/etc/nginx/nginx.conf:ro
      - $GITHUB_WORKSPACE/client_certs/ca.crt:/etc/nginx/client_certs/ca.crt:ro
      - $GITHUB_WORKSPACE/server_certs/server.crt:/etc/nginx/server.crt:ro
      - $GITHUB_WORKSPACE/server_certs/server.key:/etc/nginx/server.key:ro
    depends_on:
      sonarqube:
        condition: service_healthy
    healthcheck:
      test: 'grep -Fq "start worker processes" /var/log/nginx/access.log'
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 2m
